# import request from 'supertest';
# import { expect } from 'chai';
# import server from '../server.js';

# // Configurable expected message
# const expectedMessage = process.env.EXPECTED_MESSAGE || 'Hello, World from Group 1!';

# describe('GET /', () => {
#   it('should return Hello World message', () => {
#     return request(server)
#       .get('/')
#       .expect(200)
#       .then((res) => {
#         expect(res.text).to.equal(expectedMessage);
#       });
#   });
# });
